version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: randy
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: backend_db
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: .
    command: ["app"]
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: randy
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: backend_db
      DB_HOST: "db"
      DB_PORT: "5432"
      SECRET: "keep-it-like-a-secret"